### ISSUE TITLE
Nästa-knappen broken 

### ISSUE THREAD

**Issue by DaveMcGroin** [dtekcth/dfotose#11]
1. Gå till en sida som inte är första eller sista
2. Gå in på ett arr
3. gå in på en bild 
4. klicka på bakåt i webbläsaren två ggr
5. klicka på nästa knappen 
6. Du är nu på sida n1 istället för (n+1)

**Comment by cpluss** [comment]
resolved by bdf64cf5d86e1e236c36a54709abfd39483eeb0c
