### ISSUE TITLE
Helt tom sida på iOS 7 

### ISSUE THREAD

**Issue by SimonAlling** [dtekcth/dfotose#17]
Gissar att något i `bundle.js` inte fungerar. Det bästa skulle (av flera anledningar) förstås vara om så lite som möjligt av sajten var beroende av JavaScript.

iPad 4 
iOS 7.0.1
Safari (och likadant i Chrome)

**Comment by SimonAlling** [comment]
Försökte ladda upp screenshots, men det gick inte. Detta är all källkod jag får:

    <html><head> <title> DFoto - Datateknologsektionens Fotoförening </title> <meta name="viewport" content="width=device-width, initial-scale=1"> </head> <body> <div id="root"></div> <script src="/bundle.js"></script> </body></html>

**Comment by cpluss** [comment]
iOS7 är utdaterat, uppdatera din telefon om du vill att det ska funka dirr! Är inte riktigt hög prio att ha support för en 5 år gammal version av iOS.

Det verkar dock som om att Javascripten som hela sidan är skriven i (du är välkommen att skriva om hela frontenden om du ogillar javascript) kastar ett exception och inte kan rendera sidan. Antagligen behövs någon polyfill för att fixa support ..

**Comment by SimonAlling** [comment]
Mm, det är knappt rimligt att lägga energi på detta specifika problem, som försvinner per automatik om #18 löses på ett bra sätt.

**Comment by cpluss** [comment]
Dropping due to that iOS7 is 5 years old.
