### ISSUE TITLE
Add a robots.txt to make dfoto.se a bit harder to find

### ISSUE THREAD

**Issue by Rembane** [dtekcth/dfotose#19]
# Some sources:

https://support.google.com/webmasters/answer/6062608?hl=en
https://en.wikipedia.org/wiki/Robots_exclusion_standard#About_the_standard

# Example of robots.txt that probably does what we want
```
User-agent: *
Disallow: /
```

**Comment by BionicRiddle** [comment]
Fixed in https://github.com/dtekcth/dfotose/commit/c705bf5d27728d49a6c5031df5fbdfa0413c1e85
Closing Issue
