### ISSUE TITLE
Shiiet

### ISSUE THREAD

**Issue by cpluss** [dtekcth/dfotose#24]
@emilhem @Rembane https://dfoto.se/ redirects to dtek.se

**Comment by hallavad** [comment]
Det beror på att hackeholken kraschade för några dagar sedan och vi fortfarande håller på att sätta upp saker och ting. DFoto sidan är en av de sakerna som inte hunnit komma upp ännu

**Comment by Eethern** [comment]
Snackat med DHack och det är upp till DFoto att få upp sidan igen. Dock har jag ingen erfarenhet av hur man gör detta och låter gärna någon som kan mer om det göra det. Backups av bilder och sånt har DHack

**Comment by Rembane** [comment]
Är det samma sajt som @cpluss et. al. byggde? Eller har ni byggt något helt nytt?

**Comment by Eethern** [comment]
Det är samma

**Comment by hallavad** [comment]
Hade uppskattats av oss i dHack om sidan går att sätta upp i en docker container.
Lättare för framtida generationer att veta vad som tillhör sidan nämligen

**Comment by Rembane** [comment]
Ska vi försöka lösa det här i två steg:

1. Få upp sidan ASAP.
2. Sätta upp Docker och härja och dona på någon hackkväll eller liknande senare i höst.

Vad tror ni om den tågordningen?

**Comment by cpluss** [comment]
Det ska finnas ett script som startar upp allting i mappen, `/home/dfotose/dfotose/reload.sh` tror jag det är

**Comment by cpluss** [comment]
Se #25 så har jag en PR på docker bös, borde fungera att bara spinna upp temporärt. Allting är inte testat än dock (t.ex inloggning osv). Men om det finns en backup på den gamladatabasen kan man bara dra en `mongoimport`, slänga in bilderna på sina gamla platser (se volumes i `docker-compose.yml`), sen bara tuta o köra :)

**Comment by Rembane** [comment]
dfoto.se är uppe igen så jag stänger den här så länge. Återkom om problemet uppstår igen.
